services:
  spark-master:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://spark-master:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-worker-1:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-worker-2:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-worker-3:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
