services:
  spark-master:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=0.0.0.0  # Allow connections from all IPs
      - SPARK_LOCAL_IP=0.0.0.0     # Listen on all network interfaces
    healthcheck:
      test: ["CMD", "curl", "-f", "http://spark-master:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-worker-1:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-worker-2:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-worker-3:
    image: bitnami/spark:3.5.3-debian-12-r0
    hostname: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  prometheus_data:
  grafana_data:
