global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets:
        - 'spark-master:8080'
        - 'spark-worker-1:8081'
        - 'spark-worker-2:8081'
        - 'spark-worker-3:8081'
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
